<a href="https://colab.research.google.com/github/mtn75/Python-Toturial/blob/main/python_workshop_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [ ]:
import numpy as np

In [ ]:
import numpy
numpy.__version__

'1.21.6'

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


##Numpy Dimensions

We can create multiple dimensions arrays with Numpy.
Here are some examples of 0D, 1D, 2D, and 3D arrays:

In [ ]:
arr_0 = np.array(5)                                                         #0D array

arr_1 = np.array([1, 2, 3, 4, 5])                                           #1D array

arr_2 = np.array([[1, 2, 3], [4, 5, 6]])                                    #2D array

arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])          #3D array

print(arr_0)
print(arr_1)

5
[1 2 3 4 5]


In [ ]:
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr_3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [28]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=9)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print(x1)

[5 0 3 3 7 9]


In [ ]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [ ]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), ``size`` (the total size of the array), ``dtype`` (the data type of the array).

Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


## Access (Array Indexing)

### 1D Array Indexing

In [29]:
x1 #array

array([5, 0, 3, 3, 7, 9, 3, 5, 2])

In [30]:
x1[1]     #Access single cell

0

In [31]:
x1[3:5]       #Access multiple cells

array([3, 7])

In [32]:
x1[2:]        #Access multiple cells: from the third cell to the end

array([3, 3, 7, 9, 3, 5, 2])

In [33]:
x1[:3]        #Access multiple cells: up to the third cell (Exclusive).

array([5, 0, 3])

In [34]:
x1[-4]       #Access single cell-Negative indexing

9

In [35]:
x1[::2]  # every other element

array([5, 3, 7, 3, 2])

In [36]:
x1[1::2]  # every other element, starting at index 1

array([0, 3, 9, 5])

In [37]:
x1[::-1]  # all elements, reversed

array([2, 5, 3, 9, 7, 3, 3, 0, 5])

In [42]:
x1[5::-2]  # reversed every other from index 5

array([7, 3, 5])

In [39]:
x1[-4:-2]        #Access multiple cells- Negative indexing 

array([9, 3])

In [40]:
x1[:-2]        #Access multiple cells: up to the second cell from the last. Negative indexing (Exclusive).

array([5, 0, 3, 3, 7, 9, 3])

In [41]:
x1[-2:]        #Access multiple cells: from the second cell from the last to the end.

array([5, 2])

### Multi-Dimension Array Indexing

In [44]:
x2

array([[4, 7, 6, 8],
       [8, 1, 6, 7],
       [7, 8, 1, 5]])

In [18]:
x2[0,0]     #Access single cell

3

In [16]:
x2[1,2]     #Access single cell

8

In [17]:
x2[2,1]     #Access single cell

6

In [19]:
x2[2, -1]     #Access single cell

7

In [43]:
x2[:2, :3]  # two rows, three columns

array([[4, 7, 6],
       [8, 1, 6]])

In [45]:
x2[::-1, ::-1]

array([[5, 1, 8, 7],
       [7, 6, 1, 8],
       [8, 6, 7, 4]])

In [48]:
x2[:, 0] #first column

array([4, 8, 7])

In [49]:
x2[0, :] #first row

array([4, 7, 6, 8])

## Copy and View

Main difference: 
* Copy is a new array
* View is just a view of the original array.

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 30

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 30

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!


In [20]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])