<a href="https://colab.research.google.com/github/mtn75/Python-Toturial/blob/main/python_workshop_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [ ]:
import numpy as np

In [ ]:
import numpy
numpy.__version__

'1.21.6'

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


##Numpy Dimensions

We can create multiple dimensions arrays with Numpy.
Here are some examples of 0D, 1D, 2D, and 3D arrays:

In [ ]:
arr_0 = np.array(5)                                                         #0D array

arr_1 = np.array([1, 2, 3, 4, 5])                                           #1D array

arr_2 = np.array([[1, 2, 3], [4, 5, 6]])                                    #2D array

arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])          #3D array

print(arr_0)
print(arr_1)

5
[1 2 3 4 5]


In [ ]:
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr_3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=9) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [ ]:
print(x1)

[5 0 3 3 7 9 3 5 2]


In [ ]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [ ]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), ``size`` (the total size of the array), ``dtype`` (the data type of the array).

Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


## Access (Array Indexing)

### 1D Array Indexing

In [ ]:
x1 #array

array([5, 0, 3, 3, 7, 9, 3, 5, 2])

In [ ]:
x1[1]     #Access single cell

0

In [ ]:
x1[3:5]       #Access multiple cells

array([3, 7])

In [ ]:
x1[2:]        #Access multiple cells: from the third cell to the end

array([3, 3, 7, 9, 3, 5, 2])

In [ ]:
x1[:3]        #Access multiple cells: up to the third cell (Exclusive).

array([5, 0, 3])

In [ ]:
x1[-4]       #Access single cell-Negative indexing

9

In [ ]:
x1[::2]  # every other element

array([5, 3, 7, 3, 2])

In [ ]:
x1[1::2]  # every other element, starting at index 1

array([0, 3, 9, 5])

In [ ]:
x1[::-1]  # all elements, reversed

array([2, 5, 3, 9, 7, 3, 3, 0, 5])

In [ ]:
x1[5::-2]  # reversed every other from index 5

array([7, 3, 5])

In [ ]:
x1[-4:-2]        #Access multiple cells- Negative indexing 

array([9, 3])

In [ ]:
x1[:-2]        #Access multiple cells: up to the second cell from the last. Negative indexing (Exclusive).

array([5, 0, 3, 3, 7, 9, 3])

In [ ]:
x1[-2:]        #Access multiple cells: from the second cell from the last to the end.

array([5, 2])

### Multi-Dimension Array Indexing

In [ ]:
x2

array([[4, 7, 6, 8],
       [8, 1, 6, 7],
       [7, 8, 1, 5]])

In [ ]:
x2[0,0]     #Access single cell

4

In [ ]:
x2[1,2]     #Access single cell [row,column]

6

In [ ]:
x2[2,1]     #Access single cell

8

In [ ]:
x2[2, -1]     #Access single cell

5

In [ ]:
x2[:2, :3]  # two rows, three columns

array([[4, 7, 6],
       [8, 1, 6]])

In [ ]:
x2[::-1, ::-1]

array([[5, 1, 8, 7],
       [7, 6, 1, 8],
       [8, 6, 7, 4]])

In [ ]:
x2[:, 0] #first column

array([4, 8, 7])

In [ ]:
print(x2[0, :]) #first row

print(x2[0])  # equivalent to x2[0, :]

[4 7 6 8]
[4 7 6 8]


## Copy and View

Main difference: 
* Copy is a new array
* View is just a view of the original array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 30

print(arr)
print(x)

[30  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr[:4].view()
arr[0] = 30

print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4]


One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr[:4]
arr[0] = 30

print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr[:4]
x[0] = 30

print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4]


Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!


In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Methods

Numpy had many useful functions for reshaping the array, sorting, and so forth. 

### Reshape
You can change the dimensions of the array and reshape it to more or less dimension with the following code:

`array.reshape(dimensions)`

Here are some of the examples:

In [ ]:
arr = np.random.randint(10, size=10)  # One-dimensional array
arr

array([3, 2, 0, 7, 5, 9, 0, 2, 7, 2])

In [ ]:
arr.reshape(5,2)

array([[3, 2],
       [0, 7],
       [5, 9],
       [0, 2],
       [7, 2]])

In [ ]:
arr.reshape(2,5)

array([[3, 2, 0, 7, 5],
       [9, 0, 2, 7, 2]])

The size of the dimensions should match the number of the items:




In [ ]:
arr.reshape(2,6)

ValueError: ignored

In [ ]:
arr = np.random.randint(10, size=24)  # One-dimensional array
arr

array([6, 8, 2, 3, 0, 0, 6, 0, 6, 3, 3, 8, 8, 8, 2, 3, 2, 0, 8, 8, 3, 8,
       2, 8])

In [ ]:
arr.reshape(2,4,3)

array([[[6, 8, 2],
        [3, 0, 0],
        [6, 0, 6],
        [3, 3, 8]],

       [[8, 8, 2],
        [3, 2, 0],
        [8, 8, 3],
        [8, 2, 8]]])

### Concatenate
You can join multiple arrays with the following code:

`np.concatenate(arr1, arr2)`

Here are some examples:

In [ ]:
arr1 = np.random.randint(100, size=5)
arr2 = np.random.randint(100, size=5)

print(arr1)
print(arr2)

arr = np.concatenate((arr1, arr2))

print(arr)

[32 70 85 31 13]
[71 56 24 79 41]
[32 70 85 31 13 71 56 24 79 41]


In [ ]:
arr1 = np.random.randint(100, size=(2,3))
arr2 = np.random.randint(100, size=(2,3))

print(arr1)
print(arr2)

arr = np.concatenate((arr1, arr2))

print(arr)

[[18 40 54]
 [79 11 38]]
[[93  1 95]
 [44 88 24]]
[[18 40 54]
 [79 11 38]
 [93  1 95]
 [44 88 24]]


stack function is used if you want to concatenate two arrays along a specific axis: 

`np.stack((arr1,arr2), axis = number of axis)`

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([9, 8, 7])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 9]
 [2 8]
 [3 7]]


In [ ]:
arr = np.stack((arr1, arr2), axis=1)

print(arr)

### Split
You can split a single array into multiple array using this code:


`np.array_split(array, number of parts)`

Here are some examples:

In [ ]:
arr1 = np.random.randint(100, size=5)
print(arr1)

arr = np.array_split(arr1, 4)
print(arr)

[86 61 69 87 43]
[array([86, 61]), array([69]), array([87]), array([43])]


In [ ]:
arr1 = np.random.randint(100, size=(6,2))
print(arr1)

arr = np.array_split(arr1, 3)
print(arr)

[[69 53]
 [80 62]
 [ 8 61]
 [ 1 81]
 [35 91]
 [40 36]]
[array([[69, 53],
       [80, 62]]), array([[ 8, 61],
       [ 1, 81]]), array([[35, 91],
       [40, 36]])]


### Search

You can search for a value or a sub-array with the following code:


`np.where(condition)`

Here are some examples and conditions:


In [ ]:
arr =np.array([84, 2, 69, 12, 22, 44, 66, 91, 85, 39, 39, 75, 22])
print(arr)

[84  2 69 12 22 44 66 91 85 39 39 75 22]


In [ ]:
#Find the index of a value:
x = np.where(arr == 22)
x

(array([ 4, 12]),)

In [ ]:
#Find the index of the odd values:
x = np.where(arr%2 == 1)
x


(array([ 2,  7,  8,  9, 10, 11]),)

### Sort

You can sort the array using this code: 

`np.sort(array)`

In [ ]:
arr = np.array([3, 2, 5, 1, 4])
print(np.sort(arr))

[1 2 3 4 5]


In [ ]:
arr = np.array([[3, 2, 5], [1, 4, 6]])
print(np.sort(arr))

[[2 3 5]
 [1 4 6]]


In [ ]:
arr = np.array(['cat', 'dog', 'bird', 'ant'])
print(np.sort(arr))

['ant' 'bird' 'cat' 'dog']


In [ ]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


##Exercises

Q1:Create a 1D NumPy array with 10 random integer values between 0 and 10, and then sort it in ascending order.

Hint:To create a 1D NumPy array with 10 random integer values between 0 and 10, you can use the random.randint function from the numpy.random module. You can then use the sort function to sort the array in ascending order.


In [ ]:
#write your code here.

Q2:Create a 2D NumPy array with 5 rows and 4 columns of random integer values between 0 and 10, and then sort each row in ascending order.

Hint:
To create a 2D NumPy array with 5 rows and 4 columns of random integer values between 0 and 10, you can use the random.randint function and specify the shape of the array as (5, 4). You can then use the sort function and specify the axis parameter as 1 to sort each row in ascending order.


In [ ]:
#write your code here.

Q3:Create a 3D NumPy array with 3 matrices, each with 2 rows and 3 columns of random integer values between 0 and 10. Then, sort each matrix along the columns in descending order.

Hint:
To create a 3D NumPy array with 3 matrices, each with 2 rows and 3 columns of random integer values between 0 and 10, you can use the random.randint function and specify the shape of the array as (3, 2, 3). You can then use the sort function and specify the axis parameter as 2 to sort each matrix along the columns in descending order.


In [ ]:
#write your code here.

Q4:
Create a 1D NumPy array with 10 random floating-point values between 0 and 1, and then calculate the mean, median, and standard deviation of the array.


Hint:To calculate the mean, median, and standard deviation of a 1D NumPy array, you can use the mean, median, and std functions from the numpy module.


In [ ]:
#write your code here.

Q5:Create a 2D NumPy array with 4 rows and 5 columns of random floating-point values between 0 and 1. Then, calculate the mean of each row and column, and the standard deviation of the entire array.

Hint:
To calculate the mean of each row and column, and the standard deviation of a 2D NumPy array, you can use the mean and std functions and specify the axis parameter as 0 or 1 to calculate the mean along the rows or columns, respectively.


In [ ]:
#write your code here.

Q6:
Create a 3D NumPy array with 2 matrices, each with 3 rows and 4 columns of random floating-point values between 0 and 1. Then, calculate the mean of each matrix along the rows and columns, and the standard deviation of the entire array.

Hint:
To calculate the mean of each matrix along the rows and columns, and the standard deviation of a 3D NumPy array, you can use the mean and std functions and specify the axis parameter as (1, 2) or (2, 3) to calculate the mean along the rows or columns, respectively.


In [ ]:
#write your code here.

Q7:Create a 1D NumPy array with 10 random boolean values (True or False). Then, count the number of True values and the number of False values in the array.


Hint:To count the number of True values and the number of False values in a 1D NumPy array of boolean values, you can use the sum function and pass the array as an argument. You can then subtract the number of True values from the length of the array to get the number of False values.


In [ ]:
#write your code here.

Q8:Create a 2D NumPy array with 3 rows and 4 columns of random boolean values. Then, count the number of True values in each row and column, and the total number of True values in the entire array.


Hint:
To count the number of True values in each row and column, and the total number of True values in a 2D NumPy array of boolean values, you can use the sum function and specify the axis parameter as 0 or 1 to sum along the rows or columns, respectively.


In [ ]:
#write your code here.

Q9:Create a 3D NumPy array with 2 matrices, each with 3 rows and 4 columns of random boolean values. Then, count the number of True values in each matrix along the rows and columns, and the total number of True values in the entire array.

Hint:
To count the number of True values in each matrix along the rows and columns, and the total number of True values in a 3D NumPy array of boolean values, you can use the sum function and specify the axis parameter as (1, 2) or (2, 3) to sum along the rows or columns, respectively.

In [ ]:
#write your code here.

Q10:Create a 1D NumPy array with the values [1, 2, 3, 4, 5] and another array with the values [10, 20, 30, 40, 50]. Then, use NumPy's broadcasting capabilities to add the two arrays element-wise and create a new array with the resulting values.

Hint:To use NumPy's broadcasting capabilities to add two 1D arrays element-wise and create a new array with the resulting values, you can simply use the + operator to add the two arrays. NumPy will automatically broadcast the arrays to the same shape and perform element-wise addition.

In [ ]:
#write your code here.

# Further Reading:



*   https://www.w3schools.com/python/numpy/default.asp
*   https://numpy.org/doc/stable/user/quickstart.html
*   https://realpython.com/numpy-tutorial/

